company_list:
  - Google
  - Amazon
  - Meta
  - Microsoft
  - Apple
  - TD
  - TD Securities
  - RBC
  - Scotiabank
  - BMO
  - Manulife
  - Wealthsimple
  - Shopify
  - Intel
  - NVIDIA
  - Uber
  - IBM
  - Snowflake
  - Palantir
  - Vector Institute
  - Vanguard
  - Yelp
  - eBay
  - Lyft
  - Rogers
  - Loblaw
  - Instacart
  - Capital One
  - Ontario
  - AMD
  - EA
  - American Express
  - Interac
  - DoorDash
  - Citi
  - Oracle
  - Rakuten
  - Bloomberg
  - Deloitte
  - KPMG
  - TransUnion
  - Equifax
  - S&P
  - Cisco
  - Thomson Reuters
  - Telus
  - Bell
  - Desjardins
  - Sun Life
  - CIBC
  - National Bank of Canada
  - PwC
  - Accenture
  - Morgan Stanley
  - Candadian Tire
  - Air Canada
  - Workday
  - Intuit
  - Affirm
  - Wayfair
  - Expedia
  - Booking
  - OpenText
  - Cohere
  - Stripe
  - Pinterest

user_name: "Arron"

search:
  keyword: "Machine Learning"
  city: "Toronto, Ontario, Canada"
  distance: 10
  period: "Past 24 hours"

options:
  headless: true  # Debug - False; Production - True
  tracing: false
  trace_path: 'trace.zip'

repost: False

max_page: 10

resume: "Arron Chen Resume 2025 Updated.pdf"

salary: true # Only filter jobs that has a salary range