# List of companies that you are interested in
company_list:

# User Identification
user_name: 'User'

# Search Parameters (Required)
search:
  keyword: "Machine Learning"
  city: "Toronto, Ontario, Canada"
  distance: 10
  period: "Past 24 hours"

# Browser Settings
options:
  headless: true  # Debug - False; Production - True
  tracing: false # For internal debug only

# Whether or not to include reposted jobs (boolean)
repost: False

# Maximum page the scraper will go through
max_page: 8

# File name in /data/resumes/
resume: "resume.pdf"

salary: true # Only filter jobs that has a salary range

job_type: 'full time' # or 'co-op'/'intern'/'contract'/'rotational' Natual Language is fine

current_salary: "" # Natural language